spring.application.name=notification-service
server.port=8083

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
#spring.datasource.driver-class-name=org.postgresql.Driver

# Service URLs
services.driver-service.url=http://localhost:8082
services.rider-service.url=http://localhost:8081

## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.health.mail.enabled=false


# Logging
logging.level.com.zeta.notification_service=INFO
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{ISO8601} [%X{correlationId}] %-5level %logger{36} - %msg%n
logging.file.name=logs/notification-service.log

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# JWT
jwt.secret=MySecretKeyForJWTTokenGenerationInNotificationService2026
jwt.expiration=86400000