apiVersion: v2
name: zea-opc-b05-ridebooking-notification-service-soumyami
description: A Helm chart for zea-opc-b05-ridebooking-notification-service-soumyami
type: application
version: 0.0.1-SNAPSHOT
appVersion: "0.0.1"
dependencies:
  - name: common
    version: 1.0.98
    repository: '@chartrepo'