-- V1__create_rider_ride_payment_tables.sql

-- 1. Create Riders Table
CREATE TABLE riders (
    rider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    total_rides INTEGER DEFAULT 0,
    status VARCHAR(50) DEFAULT 'ACTIVE', -- Enum stored as String
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 2. Create Rides Table
CREATE TABLE rides (
    ride_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id BIGINT NOT NULL,
    driver_id BIGINT,
    pickup_latitude DOUBLE PRECISION NOT NULL,
    pickup_longitude DOUBLE PRECISION NOT NULL,
    pickup_address VARCHAR(255),
    drop_latitude DOUBLE PRECISION NOT NULL,
    drop_longitude DOUBLE PRECISION NOT NULL,
    drop_address VARCHAR(255),
    status VARCHAR(50) NOT NULL, -- Enum stored as String
    fare_amount NUMERIC(19, 2),  -- BigDecimal mapping
    distance_km DOUBLE PRECISION,
    requested_at TIMESTAMP,
    assigned_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    cancellation_reason VARCHAR(255),
    version BIGINT,              -- For Optimistic Locking
    idempotency_key VARCHAR(255),

    -- Constraint: Link ride to the rider
    CONSTRAINT fk_rides_rider FOREIGN KEY (rider_id) REFERENCES riders (rider_id)
);

-- 3. Create Payments Table
CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id BIGINT NOT NULL,
    rider_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL, -- Enum stored as String
    payment_status VARCHAR(50) NOT NULL, -- Mapped via @Column(name = "payment_status")
    transaction_id VARCHAR(255),
    payment_date TIMESTAMP,
    created_at TIMESTAMP,

    -- Constraints: Link payment to ride and rider
    CONSTRAINT fk_payments_ride FOREIGN KEY (ride_id) REFERENCES rides (ride_id),
    CONSTRAINT fk_payments_rider FOREIGN KEY (rider_id) REFERENCES riders (rider_id)
);

-- Optional: Create Indexes for performance on frequently queried columns
CREATE INDEX idx_rides_rider_id ON rides(rider_id);
CREATE INDEX idx_payments_ride_id ON payments(ride_id);
CREATE INDEX idx_payments_rider_id ON payments(rider_id);