-- 1. Create table for Driver
CREATE TABLE drivers (
    driver_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    license_number VARCHAR(255) NOT NULL,
    vehicle_number VARCHAR(255) NOT NULL,
    vehicle_type VARCHAR(255) NOT NULL,
    total_rides INTEGER DEFAULT 0,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT,

    -- Unique Constraints defined in Entity
    CONSTRAINT uq_drivers_email UNIQUE (email),
    CONSTRAINT uq_drivers_phone UNIQUE (phone),
    CONSTRAINT uq_drivers_license_number UNIQUE (license_number)
);

-- 2. Create table for Driver Availability
CREATE TABLE driver_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    available BOOLEAN NOT NULL,
    current_ride_id BIGINT,
    updated_at TIMESTAMP,

    -- Foreign Key Constraint (Recommended for data integrity)
    CONSTRAINT fk_driver_availability_driver
        FOREIGN KEY (driver_id)
        REFERENCES drivers (driver_id)
        ON DELETE CASCADE
);

-- 3. Create table for Driver Earnings
CREATE TABLE driver_earnings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    ride_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL, -- Standard precision for BigDecimal currency
    earned_at TIMESTAMP,

    -- Foreign Key Constraint
    CONSTRAINT fk_driver_earnings_driver
        FOREIGN KEY (driver_id)
        REFERENCES drivers (driver_id)
        ON DELETE CASCADE
);

-- 4. Create table for Driver Locations
CREATE TABLE driver_locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    current_latitude DOUBLE PRECISION NOT NULL,
    current_longitude DOUBLE PRECISION NOT NULL,
    heading DOUBLE PRECISION,
    speed_kmph DOUBLE PRECISION,
    updated_at TIMESTAMP,

    -- Foreign Key Constraint
    CONSTRAINT fk_driver_locations_driver
        FOREIGN KEY (driver_id)
        REFERENCES drivers (driver_id)
        ON DELETE CASCADE
);

-- Optional: Indexes for frequently queried columns (Best Practice)
CREATE INDEX idx_driver_availability_driver_id ON driver_availability(driver_id);
CREATE INDEX idx_driver_earnings_driver_id ON driver_earnings(driver_id);
CREATE INDEX idx_driver_locations_driver_id ON driver_locations(driver_id);